replicaCount: 4

image:
  repository: "vee101/backend"
  tag: "9ae5a0a5605f8e71c5f0aa59393ad8cc2589e8ef"
  pullPolicy: IfNotPresent

service:
  port: 4005

env:
  APP_NAME: "Application"
  PORT: "4005"
