replicaCount: 4

image:
  repository: "vee101/backend"
  tag: "2dca29f18e57a79fbf5553714c990904b8a6f86a"
  pullPolicy: IfNotPresent

service:
  port: 4005

env:
  APP_NAME: "Application"
  PORT: "4005"
