---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backend-secret
  namespace: default
spec:
  encryptedData:
    MONGO_URI: AgAhGBVHFt9WfYkr+T3DBEdcOkvHwcmWnJ46jpa2f6STzXV7SZY7FUnm+ygg0XuF6KixOyKBviGOcT5OTnJ+rhDuDUWLrF2XPdrZ1x1dSoD7KoWKJt/oESLq71GjNICcC4gELll3tUCjhrYcmH3C9aO+iR9rLGscRHH08+piNccQjVFxZmBsYDoiST2gfXz61S3eVw6Wu3Q5xi/Cre/ZiKvVsnoOeYqpGT1QH8pPFeDT9LZKOyrOOiTex3dO3gAtWs/HTBSlxqNcQ5bBfJ6UZQU6iLQu6vrmNjlIapjqwVp2tuDmuiO+/4P79K2CwL3dNnIRYfx1TrNPPpODPO0yPiPzq55dtbW2f2yzw4IiNUS9gFKdl6HGJPp/yBt1Ccl7Drd7/JxoL1R6wwgIJVY3ZhYJy2X6Jyp/KW3NprY/ppouwj3KOkQeVx8yCphdCGNfyG1YT+MI46c/7lWpOvtaEScZwu20Qg161ifkRjhseYy0Z1ev1qVQgJtHInogGzn8IT/C5xdWEL9QfI8Gjxb6aPT+STM163yzmtg9a2hLeSO0q6BEcXzQbH/5o9pDsWy3m4qDwPTrA7YEG/fCFaRf1bwyDVc/UCSVFJrM6rHTzn+jXxkd3hH+H+cziP7WJd90LbBByhlSiOfDOXtHC08RaFdecB+2GPbNknMWdICk8/icPZkhJTPOjlup54KgYEToKFWuFrcuUe5WXmkCMYyErhvZZ8mIfHx3wxDDXjO2/fcj3KoFy8gu3IQTUlUt+3jRtM9p+l1sgEAutK8+J+tjNsnHfb2MohWXYwtClyQ8aOeSrcHILQ5IZPJMLBjys05v0PhSKwpKP3mlrhc=
  template:
    metadata:
      name: backend-secret
      namespace: default
