apiVersion: v1
kind: Service
metadata:
  name: backend-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: backend-pod
  ports:
    - port: 4004
      targetPort: {{ .Values.service.port }}
  type: ClusterIP